#!/usr/bin/env tsx
/**
 * Data expansion script: reads data/distros.json and adds hundreds of additional
 * Linux distros sourced from Wikipedia's "List of Linux distributions" and
 * DistroWatch, organized by family.
 *
 * Usage: npx tsx scripts/expand-data.ts
 *
 * This will output data/distros.json with 400+ distros.
 * Then run: npm run build:data to regenerate the frontend data files.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import type { SourceData, SourceDistro, SourceFamily } from '../shared/types';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(__dirname, '..');
const SRC = resolve(ROOT, 'data/distros.json');

// Current data
const current = JSON.parse(readFileSync(SRC, 'utf-8')) as SourceData;

// Build lookup sets for dedup
const existingDistroIds = new Set(current.distros.map((d) => d.id));
const existingFamilyIds = new Set(current.families.map((f) => f.id));
const existingColors = new Set(current.families.map((f) => f.color));

/** Generate a unique, deterministic color for a new family */
function genColor(id: string, seed = 42): string {
  let h = seed;
  for (let i = 0; i < id.length; i++) {
    h = ((h << 5) - h + id.charCodeAt(i)) | 0;
  }
  const hue = Math.abs(h) % 360;
  // Avoid very light or very dark colors
  return `hsl(${hue}, 55%, 40%)`;
}

function addDistro(d: SourceDistro) {
  if (!existingDistroIds.has(d.id)) {
    current.distros.push(d);
    existingDistroIds.add(d.id);
  }
}

function addFamily(f: SourceFamily) {
  if (!existingFamilyIds.has(f.id)) {
    if (!existingColors.has(f.color)) {
      existingColors.add(f.color);
    } else {
      // Pick a unique color
      f.color = genColor(f.id);
    }
    current.families.push(f);
    existingFamilyIds.add(f.id);
  }
}

/* ==========================================================================
   NEW FAMILIES
   ========================================================================== */

addFamily({ id: 'antergos', name: 'Antergos', color: '#23a3e0', description: 'Discontinued Arch-based distro with a graphical installer.', founded: 2012, rootDistroId: 'antergos' });
addFamily({ id: 'parabola', name: 'Parabola', color: '#337733', description: 'Arch-based fully free software distribution.', founded: 2009, rootDistroId: 'parabola' });
addFamily({ id: 'hyperbola', name: 'Hyperbola', color: '#cc3333', description: 'Arch/Debian-based free software distribution with OpenRC.', founded: 2017, rootDistroId: 'hyperbola' });
addFamily({ id: 'kaos', name: 'KaOS', color: '#e6a817', description: 'Independent rolling-release distro focused on KDE Plasma and Qt.', founded: 2009, rootDistroId: 'kaos' });
addFamily({ id: 'chakra', name: 'Chakra', color: '#3d9e3d', description: 'Discontinued Arch-derived distro focused on KDE and Qt.', founded: 2006, rootDistroId: 'chakra' });
addFamily({ id: 'scientific', name: 'Scientific Linux', color: '#0055aa', description: 'Discontinued RHEL-based distro from CERN/Fermilab.', founded: 2004, rootDistroId: 'scientific' });
addFamily({ id: 'clearos', name: 'ClearOS', color: '#0099dd', description: 'RHEL-based distro for small and medium enterprises.', founded: 2000, rootDistroId: 'clearos' });
addFamily({ id: 'pclinuxos', name: 'PCLinuxOS', color: '#228b22', description: 'Rolling-release RPM-based distro for desktops.', founded: 2003, rootDistroId: 'pclinuxos' });
addFamily({ id: 'altlinux', name: 'ALT Linux', color: '#cc6600', description: 'Russian RPM-based distribution family.', founded: 2001, rootDistroId: 'altlinux' });
addFamily({ id: 'rosa', name: 'ROSA', color: '#cc0033', description: 'Russian Mandriva-based distribution.', founded: 2010, rootDistroId: 'rosa' });
addFamily({ id: 'redflag', name: 'Red Flag', color: '#cc0000', description: 'Chinese RPM-based distribution.', founded: 1999, rootDistroId: 'redflag' });
addFamily({ id: 'turbolinux', name: 'TurboLinux', color: '#0066aa', description: 'Japanese RPM-based distribution.', founded: 1992, rootDistroId: 'turbolinux' });
addFamily({ id: 'lineageos', name: 'LineageOS', color: '#167c80', description: 'Android-based mobile OS, fork of CyanogenMod.', founded: 2016, rootDistroId: 'lineageos' });
addFamily({ id: 'grapheneos', name: 'GrapheneOS', color: '#4488dd', description: 'Privacy and security hardened Android-based OS.', founded: 2014, rootDistroId: 'grapheneos' });
addFamily({ id: 'calyxos', name: 'CalyxOS', color: '#44aa55', description: 'Android-based OS focused on privacy and security.', founded: 2018, rootDistroId: 'calyxos' });
addFamily({ id: 'e-os', name: '/e/ OS', color: '#aa44cc', description: 'Android-based de-Googled mobile OS.', founded: 2018, rootDistroId: 'e-os' });
addFamily({ id: 'replicant', name: 'Replicant', color: '#44aa88', description: 'Fully free Android-based OS.', founded: 2010, rootDistroId: 'replicant' });
addFamily({ id: 'coreos', name: 'CoreOS', color: '#3673b0', description: 'Discontinued container-focused Linux for clustered deployments.', founded: 2013, rootDistroId: 'coreos' });
addFamily({ id: 'clear-linux', name: 'Clear Linux', color: '#4488cc', description: 'Intel\'s performance-optimized rolling release Linux.', founded: 2015, rootDistroId: 'clear-linux' });
addFamily({ id: 'crux', name: 'CRUX', color: '#557799', description: 'Lightweight, x86-64 optimized Linux, inspiration for Arch.', founded: 2001, rootDistroId: 'crux' });
addFamily({ id: 'gobolinux', name: 'GoboLinux', color: '#8866aa', description: 'Alternative filesystem hierarchy Linux distribution.', founded: 2003, rootDistroId: 'gobolinux' });
addFamily({ id: 'tinycore', name: 'Tiny Core', color: '#99aacc', description: 'Minimalist Linux distribution (~10 MB).', founded: 2009, rootDistroId: 'tinycore' });
addFamily({ id: 'dragora', name: 'Dragora', color: '#338833', description: 'Free software distribution written from scratch.', founded: 2008, rootDistroId: 'dragora' });
addFamily({ id: 'guix', name: 'Guix System', color: '#ddaa00', description: 'Declarative GNU distribution with purely functional package management.', founded: 2012, rootDistroId: 'guix' });
addFamily({ id: 'bedrock', name: 'Bedrock Linux', color: '#886644', description: 'Meta-distribution allowing mixing components from other distros.', founded: 2012, rootDistroId: 'bedrock' });
addFamily({ id: 'zenwalk', name: 'Zenwalk', color: '#44aadd', description: 'Lightweight Slackware-based distribution.', founded: 2004, rootDistroId: 'zenwalk' });
addFamily({ id: 'slax', name: 'Slax', color: '#4488dd', description: 'Portable, modular live Linux distribution based on Slackware.', founded: 2002, rootDistroId: 'slax' });
addFamily({ id: '4mlinux', name: '4MLinux', color: '#77aacc', description: 'Small, independent general-purpose Linux distribution.', founded: 2010, rootDistroId: '4mlinux' });
addFamily({ id: 'chimera', name: 'Chimera Linux', color: '#4488aa', description: 'Independent Linux using FreeBSD utilities, LLVM, and musl.', founded: 2021, rootDistroId: 'chimera' });

/* ==========================================================================
   EXPANDED DISTROS BY FAMILY
   ========================================================================== */

// ---- Debian family - add more Debian-based distros ----
addDistro({ id: 'sparkylinux', parent: 'debian', familyId: 'debian', name: 'SparkyLinux', status: 'active', founded: 2012, country: 'Poland', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://sparkylinux.org', wikipedia: 'https://en.wikipedia.org/wiki/SparkyLinux', description: 'Debian-based lightweight distribution with a focus on speed.' });
addDistro({ id: 'q4os', parent: 'debian', familyId: 'debian', name: 'Q4OS', status: 'active', founded: 2013, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://q4os.org', description: 'Debian-based lightweight distro with Trinity or Plasma desktop.' });
addDistro({ id: 'mepis', parent: 'debian', familyId: 'debian', name: 'MEPIS', status: 'discontinued', founded: 2003, discontinuedAt: 2014, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://mepis.org', wikipedia: 'https://en.wikipedia.org/wiki/MEPIS', description: 'Debian-based distro, precursor to MX Linux. Discontinued.' });
addDistro({ id: 'kanotix', parent: 'debian', familyId: 'debian', name: 'Kanotix', status: 'discontinued', founded: 2003, discontinuedAt: 2014, country: 'Germany', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://kanotix.com', description: 'Debian-based live DVD with KDE and LXDE.' });
addDistro({ id: 'siduction', parent: 'debian', familyId: 'debian', name: 'Siduction', status: 'active', founded: 2012, country: 'Germany', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://siduction.org', description: 'Debian Sid-based rolling release distro.' });
addDistro({ id: 'proxmox', parent: 'debian', familyId: 'debian', name: 'Proxmox VE', status: 'active', founded: 2008, country: 'Austria', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://proxmox.com', wikipedia: 'https://en.wikipedia.org/wiki/Proxmox_Virtual_Environment', description: 'Debian-based virtualization platform with KVM and LXC.' });
addDistro({ id: 'turnkey', parent: 'debian', familyId: 'debian', name: 'TurnKey Linux', status: 'active', founded: 2009, country: 'Australia', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://turnkeylinux.org', description: 'Debian-based appliance library for servers.' });
addDistro({ id: 'vyos', parent: 'debian', familyId: 'debian', name: 'VyOS', status: 'active', founded: 2013, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://vyos.io', description: 'Debian-based network operating system with routing and firewall.' });
addDistro({ id: 'grml', parent: 'debian', familyId: 'debian', name: 'grml', status: 'active', founded: 2005, country: 'Austria', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://grml.org', wikipedia: 'https://en.wikipedia.org/wiki/Grml', description: 'Debian-based system rescue live CD.' });
addDistro({ id: 'astra', parent: 'debian', familyId: 'debian', name: 'Astra Linux', status: 'active', founded: 2008, country: 'Russia', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://astralinux.com', wikipedia: 'https://en.wikipedia.org/wiki/Astra_Linux', description: 'Russian Debian-based distribution certified for military use.' });
addDistro({ id: 'boss', parent: 'debian', familyId: 'debian', name: 'BOSS Linux', status: 'active', founded: 2007, country: 'India', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://bosslinux.in', wikipedia: 'https://en.wikipedia.org/wiki/Bharat_Operating_System_Solutions', description: 'Indian Debian-based distribution by C-DAC.' });
addDistro({ id: 'pardus', parent: 'debian', familyId: 'debian', name: 'Pardus', status: 'active', founded: 2013, country: 'Turkey', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://pardus.org.tr', wikipedia: 'https://en.wikipedia.org/wiki/Pardus_(operating_system)', description: 'Turkish Debian-based distribution by TÜBİTAK.' });
addDistro({ id: 'canaima', parent: 'debian', familyId: 'debian', name: 'Canaima', status: 'active', founded: 2009, country: 'Venezuela', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://canaima.softwarelibre.gob.ve', description: 'Venezuelan Debian-based distribution.' });
addDistro({ id: 'sober', parent: 'debian', familyId: 'debian', name: 'Sober Linux', status: 'discontinued', founded: 2019, discontinuedAt: 2023, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', description: 'Aesthetic, beginner-friendly Debian-based distro aimed at newcomers.' });
addDistro({ id: 'damn-small-linux', parent: 'knoppix', familyId: 'debian', name: 'Damn Small Linux', status: 'discontinued', founded: 2005, discontinuedAt: 2008, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://damnsmalllinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Damn_Small_Linux', description: 'Tiny Linux distro designed to run on older hardware.' });
addDistro({ id: 'finnix', parent: 'debian', familyId: 'debian', name: 'Finnix', status: 'active', founded: 2000, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://finnix.org', description: 'Small system-administration live CD for multiple architectures.' });
addDistro({ id: 'elive', parent: 'debian', familyId: 'debian', name: 'Elive', status: 'active', founded: 2005, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://elive.org', description: 'Debian-based distro featuring the Enlightenment desktop.' });
addDistro({ id: 'webconverger', parent: 'debian', familyId: 'debian', name: 'Webconverger', status: 'active', founded: 2007, country: 'United Kingdom', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://webconverger.com', description: 'Browser-only Debian Live-based distribution for public places.' });

// ---- Ubuntu - add more unofficial Ubuntu derivatives ----
addDistro({ id: 'linuxlite', parent: 'ubuntu', familyId: 'ubuntu', name: 'Linux Lite', status: 'active', founded: 2012, country: 'New Zealand', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://linuxliteos.com', wikipedia: 'https://en.wikipedia.org/wiki/Linux_Lite', description: 'Lightweight Ubuntu-based distro with Xfce, aimed at Windows migrants.' });
addDistro({ id: 'karoshi', parent: 'ubuntu', familyId: 'ubuntu', name: 'Karoshi', status: 'discontinued', founded: 2005, discontinuedAt: 2016, country: 'United Kingdom', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://karoshi.org.uk', description: 'Ubuntu-based distribution designed for schools.' });
addDistro({ id: 'galliumos', parent: 'xubuntu', familyId: 'ubuntu', name: 'GalliumOS', status: 'active', founded: 2016, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://galliumos.org', wikipedia: 'https://en.wikipedia.org/wiki/GalliumOS', description: 'Xubuntu-based distro optimized for ChromeOS devices.' });
addDistro({ id: 'lxle', parent: 'lubuntu', familyId: 'ubuntu', name: 'LXLE Linux', status: 'active', founded: 2015, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'lts', license: 'Free', website: 'https://lxle.net', description: 'Lightweight Lubuntu-based distro for older hardware.' });
addDistro({ id: 'uberstudent', parent: 'ubuntu', familyId: 'ubuntu', name: 'UberStudent', status: 'discontinued', founded: 2009, discontinuedAt: 2020, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://uberstudent.org', description: 'Ubuntu-based distro for higher education students.' });
addDistro({ id: 'dynebolic', parent: 'ubuntu', familyId: 'ubuntu', name: 'dyne:bolic', status: 'discontinued', founded: 2005, discontinuedAt: 2015, country: 'Italy', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://dyne.org', description: 'Live CD geared toward multimedia production.' });
addDistro({ id: 'netrunner', parent: 'kubuntu', familyId: 'ubuntu', name: 'Netrunner', status: 'active', founded: 2009, country: 'Germany', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://netrunner.com', description: 'Kubuntu-based distro with full codecs and software.' });
addDistro({ id: 'freespire', parent: 'ubuntu', familyId: 'ubuntu', name: 'Freespire', status: 'active', founded: 2006, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'lts', license: 'Free', website: 'https://freespire.net', description: 'Ubuntu-based community distro from the Linspire family.' });
addDistro({ id: 'linspire', parent: 'ubuntu', familyId: 'ubuntu', name: 'Linspire', status: 'active', founded: 2001, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'lts', license: 'Proprietary', website: 'https://linspirelinux.com', wikipedia: 'https://en.wikipedia.org/wiki/Linspire', description: 'Commercial Ubuntu-based distro focused on ease of use.' });
addDistro({ id: 'lliurex', parent: 'ubuntu', familyId: 'ubuntu', name: 'LliureX', status: 'active', founded: 2005, country: 'Spain', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://lliurex.net', description: 'Ubuntu-based distribution by the Generalitat Valenciana for education.' });
addDistro({ id: 'maxlinux', parent: 'ubuntu', familyId: 'ubuntu', name: 'MAX Linux', status: 'active', founded: 2011, country: 'Spain', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://edulibre.net', description: 'Madrid Linux distribution used in education.' });
addDistro({ id: 'linkat', parent: 'ubuntu', familyId: 'ubuntu', name: 'Linkat', status: 'active', founded: 2005, country: 'Spain', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://linkat.cat', description: 'Ubuntu-based distribution for Catalan schools.' });
addDistro({ id: 'gooroom', parent: 'ubuntu', familyId: 'ubuntu', name: 'Gooroom', status: 'active', founded: 2015, country: 'South Korea', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://gooroom.kr', description: 'South Korean government Ubuntu-based distribution.' });
addDistro({ id: 'elementos', parent: 'xubuntu', familyId: 'ubuntu', name: 'Element OS', status: 'discontinued', founded: 2008, discontinuedAt: 2015, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://elementos.org', description: 'Xubuntu-based HTPC distribution.' });
addDistro({ id: 'opengeu', parent: 'ubuntu', familyId: 'ubuntu', name: 'OpenGEU', status: 'discontinued', founded: 2007, discontinuedAt: 2012, country: 'Brazil', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', description: 'Ubuntu-based distro with Enlightenment window manager.' });
addDistro({ id: 'emma', parent: 'xubuntu', familyId: 'ubuntu', name: 'Emmabuntüs', status: 'active', founded: 2012, country: 'France', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://emmabuntus.org', description: 'Xubuntu-based distro for refurbished computers.' });
addDistro({ id: 'winux', parent: 'ubuntu', familyId: 'ubuntu', name: 'Winux', status: 'active', founded: 2022, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://wubuntu.org', description: 'Ubuntu-based distro designed to mimic Windows 11 interface.' });
addDistro({ id: 'maui', parent: 'ubuntu', familyId: 'ubuntu', name: 'Maui Linux', status: 'discontinued', founded: 2015, discontinuedAt: 2019, country: 'Germany', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://mauilinux.org', description: 'Ubuntu-based distro with Plasma desktop. Discontinued.' });
addDistro({ id: 'trisquel-pro', parent: 'trisquel', familyId: 'trisquel', name: 'Trisquel Pro', status: 'active', founded: 2007, country: 'Spain', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://trisquel.info', description: 'Trisquel edition with extra libre packages for professional use.' });
addDistro({ id: 'gnewsense', parent: 'ubuntu', familyId: 'trisquel', name: 'gNewSense', status: 'discontinued', founded: 2006, discontinuedAt: 2014, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://gnewsense.org', wikipedia: 'https://en.wikipedia.org/wiki/GNewSense', description: 'FSF-endorsed fully free Debian/Ubuntu derivative.' });

// ---- antiX family ----
addDistro({ id: 'antix', familyId: 'antix', name: 'antiX', status: 'active', founded: 2004, country: 'Global', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://antixlinux.com', wikipedia: 'https://en.wikipedia.org/wiki/AntiX', description: 'Fast, lightweight Debian-based live distro for old hardware.' });
addDistro({ id: 'antix-full', parent: 'antix', familyId: 'antix', name: 'antiX Full', status: 'active', founded: 2007, country: 'Global', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://antixlinux.com', description: 'Full edition of antiX with a complete set of applications.' });
addDistro({ id: 'antix-core', parent: 'antix', familyId: 'antix', name: 'antiX Core', status: 'active', founded: 2007, country: 'Global', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://antixlinux.com', description: 'Minimal antiX edition with just the core system.' });
addDistro({ id: 'antix-base', parent: 'antix', familyId: 'antix', name: 'antiX Base', status: 'active', founded: 2007, country: 'Global', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://antixlinux.com', description: 'Base antiX edition with a moderate selection of apps.' });

// ---- MX family ----
addDistro({ id: 'mx', parent: 'antix', familyId: 'mx', name: 'MX Linux', status: 'active', founded: 2014, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://mxlinux.org', wikipedia: 'https://en.wikipedia.org/wiki/MX_Linux', description: 'Midweight Debian-stable-based distro with Xfce.' });
addDistro({ id: 'mx-kde', parent: 'mx', familyId: 'mx', name: 'MX Linux KDE', status: 'active', founded: 2019, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'semi-rolling', license: 'Free', website: 'https://mxlinux.org', description: 'MX Linux edition with KDE Plasma desktop.' });
addDistro({ id: 'mx-fluxbox', parent: 'mx', familyId: 'mx', name: 'MX Linux Fluxbox', status: 'active', founded: 2020, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'semi-rolling', license: 'Free', website: 'https://mxlinux.org', description: 'Lightweight MX edition with Fluxbox window manager.' });

// ---- Devuan - add more ----
addDistro({ id: 'exegnu', parent: 'devuan', familyId: 'devuan', name: 'Exe GNU/Linux', status: 'active', founded: 2014, country: 'Germany', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://exegnu.org', description: 'Devuan-based FSDG-compliant distribution.' });
addDistro({ id: 'refracta', parent: 'devuan', familyId: 'devuan', name: 'Refracta', status: 'active', founded: 2014, country: 'United States', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://refracta.org', description: 'Devuan-based easy-to-install distribution.' });
addDistro({ id: 'devuan-beowulf', parent: 'devuan', familyId: 'devuan', name: 'Devuan Beowulf', status: 'active', founded: 2020, country: 'Global', packageManager: 'apt', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://devuan.org', description: 'Devuan stable release based on Debian Buster.' });

// ---- Arch - add more Arch derivatives and tools ----
addDistro({ id: 'archinstall', parent: 'arch', familyId: 'arch', name: 'archinstall', status: 'active', founded: 2021, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', description: 'Official guided installer for Arch Linux.' });
addDistro({ id: 'antergos', parent: 'arch', familyId: 'antergos', name: 'Antergos', status: 'discontinued', founded: 2012, discontinuedAt: 2019, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://antergos.com', wikipedia: 'https://en.wikipedia.org/wiki/Antergos', description: 'Discontinued Arch-based distro with a friendly graphical installer.' });
addDistro({ id: 'archbang', parent: 'arch', familyId: 'arch', name: 'ArchBang', status: 'active', founded: 2011, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://archbang.org', description: 'Minimal Arch-based distro with i3 window manager.' });
addDistro({ id: 'archlabs', parent: 'arch', familyId: 'arch', name: 'ArchLabs', status: 'discontinued', founded: 2016, discontinuedAt: 2021, country: 'Australia', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://archlabslinux.com', description: 'Arch-based distro focused on Openbox with custom installer.' });
addDistro({ id: 'rebornos', parent: 'arch', familyId: 'arch', name: 'Reborn OS', status: 'active', founded: 2018, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://rebornos.org', description: 'Arch-based distro with multiple desktop environment choices.' });
addDistro({ id: 'xerolinux', parent: 'arch', familyId: 'arch', name: 'XeroLinux', status: 'active', founded: 2021, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://xerolinux.xyz', description: 'Aesthetic Arch-based distro with KDE Plasma.' });
addDistro({ id: 'alci', parent: 'arch', familyId: 'arch', name: 'ALCI', status: 'active', founded: 2020, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://alci.online', description: 'Arch Linux Calamares Installer — simple Arch installation.' });
addDistro({ id: 'parabola', parent: 'arch', familyId: 'parabola', name: 'Parabola GNU/Linux-libre', status: 'active', founded: 2009, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://parabola.nu', wikipedia: 'https://en.wikipedia.org/wiki/Parabola_GNU/Linux-libre', description: 'FSF-endorsed fully free Arch derivative.' });
addDistro({ id: 'hyperbola', parent: 'parabola', familyId: 'hyperbola', name: 'Hyperbola GNU/Linux-libre', status: 'active', founded: 2017, country: 'Global', packageManager: 'pacman', initSystem: 'OpenRC', releaseModel: 'fixed', license: 'Free', website: 'https://hyperbola.info', description: 'Arch/Debian-based free distro without systemd.' });
addDistro({ id: 'systemrescue', parent: 'arch', familyId: 'arch', name: 'SystemRescue', status: 'active', founded: 2000, country: 'France', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://system-rescue.org', wikipedia: 'https://en.wikipedia.org/wiki/SystemRescue', description: 'System rescue toolkit, based on Arch since v6.0.' });
addDistro({ id: 'steamos', parent: 'arch', familyId: 'arch', name: 'SteamOS', status: 'active', founded: 2013, country: 'United States', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://store.steampowered.com/steamos', wikipedia: 'https://en.wikipedia.org/wiki/SteamOS', description: 'Valve\'s Arch-based gaming OS for Steam Deck.' });

// ---- Manjaro - add more editions ----
addDistro({ id: 'manjaro-sway', parent: 'manjaro', familyId: 'manjaro', name: 'Manjaro Sway', status: 'active', founded: 2022, country: 'Germany', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://manjaro.org', description: 'Manjaro edition with the Sway tiling compositor.' });
addDistro({ id: 'manjaro-budgie', parent: 'manjaro', familyId: 'manjaro', name: 'Manjaro Budgie', status: 'active', founded: 2019, country: 'Germany', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://manjaro.org', description: 'Manjaro edition with Budgie desktop.' });
addDistro({ id: 'manjaro-arm', parent: 'manjaro', familyId: 'manjaro', name: 'Manjaro ARM', status: 'active', founded: 2017, country: 'Germany', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://manjaro.org', description: 'Manjaro port for ARM devices like Raspberry Pi.' });

// ---- Fedora - add more spins and derivatives ----
addDistro({ id: 'fedora-workstation', parent: 'fedora', familyId: 'fedora', name: 'Fedora Workstation', status: 'active', founded: 2003, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora edition for desktops and laptops with GNOME.' });
addDistro({ id: 'fedora-server', parent: 'fedora', familyId: 'fedora', name: 'Fedora Server', status: 'active', founded: 2003, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora edition for servers.' });
addDistro({ id: 'fedora-iot', parent: 'fedora', familyId: 'fedora', name: 'Fedora IoT', status: 'active', founded: 2018, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora edition for Internet of Things deployments.' });
addDistro({ id: 'fedora-kde', parent: 'fedora', familyId: 'fedora', name: 'Fedora KDE Plasma', status: 'active', founded: 2003, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with KDE Plasma.' });
addDistro({ id: 'fedora-xfce', parent: 'fedora', familyId: 'fedora', name: 'Fedora Xfce', status: 'active', founded: 2005, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with Xfce.' });
addDistro({ id: 'fedora-cinnamon', parent: 'fedora', familyId: 'fedora', name: 'Fedora Cinnamon', status: 'active', founded: 2013, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with Cinnamon desktop.' });
addDistro({ id: 'fedora-mate', parent: 'fedora', familyId: 'fedora', name: 'Fedora MATE', status: 'active', founded: 2008, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with MATE desktop.' });
addDistro({ id: 'fedora-budgie', parent: 'fedora', familyId: 'fedora', name: 'Fedora Budgie', status: 'active', founded: 2020, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with Budgie desktop.' });
addDistro({ id: 'fedora-sway', parent: 'fedora', familyId: 'fedora', name: 'Fedora Sway', status: 'active', founded: 2020, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fedoraproject.org', description: 'Fedora spin with Sway tiling compositor.' });
addDistro({ id: 'nobara', parent: 'fedora', familyId: 'fedora', name: 'Nobara Linux', status: 'active', founded: 2020, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://nobaraproject.org', description: 'Fedora-based gaming and streaming distro by GloriousEggroll.' });
addDistro({ id: 'bazzite', parent: 'fedora', familyId: 'fedora', name: 'Bazzite', status: 'active', founded: 2022, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://bazzite.org', description: 'Atomic Fedora-based gaming distro built with Universal Blue.' });
addDistro({ id: 'korora', parent: 'fedora', familyId: 'fedora', name: 'Korora', status: 'discontinued', founded: 2005, discontinuedAt: 2018, country: 'Australia', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://kororaproject.org', description: 'Fedora-based distro with preconfigured desktop options.' });
addDistro({ id: 'asahi', parent: 'fedora', familyId: 'fedora', name: 'Asahi Linux', status: 'active', founded: 2021, country: 'Global', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://asahilinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Asahi_Linux', description: 'Port of Linux to Apple Silicon Macs, based on Fedora.' });
addDistro({ id: 'sugar', parent: 'fedora', familyId: 'fedora', name: 'Sugar-on-a-Stick', status: 'active', founded: 2008, country: 'United States', packageManager: 'dnf', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://spins.fedoraproject.org/sugar', description: 'Fedora-based educational OS from One Laptop Per Child.' });

// ---- RHEL-based ----
addDistro({ id: 'scientific', parent: 'rhel', familyId: 'scientific', name: 'Scientific Linux', status: 'discontinued', founded: 2004, discontinuedAt: 2020, country: 'United States', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://scientificlinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Scientific_Linux', description: 'RHEL-based distro from CERN and Fermilab. Discontinued.' });
addDistro({ id: 'clearos', parent: 'rhel', familyId: 'clearos', name: 'ClearOS', status: 'active', founded: 2000, country: 'United States', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://clearos.com', description: 'RHEL-based server distribution for SMBs.' });
addDistro({ id: 'fermi', parent: 'scientific', familyId: 'scientific', name: 'Fermi Linux LTS', status: 'active', founded: 2004, country: 'United States', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://fermilinux.fnal.gov', description: 'Fermilab-managed Scientific Linux LTS release.' });
addDistro({ id: 'redflag', parent: 'rhel', familyId: 'redflag', name: 'Red Flag Linux', status: 'active', founded: 1999, country: 'China', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://redflag-linux.com', wikipedia: 'https://en.wikipedia.org/wiki/Red_Flag_Linux', description: 'Chinese RHEL-based distribution.' });
addDistro({ id: 'miracle', parent: 'rhel', familyId: 'rhel', name: 'Miracle Linux', status: 'active', founded: 2001, country: 'Japan', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://miraclelinux.com', description: 'Japanese RHEL-compatible distribution.' });
addDistro({ id: 'rocks', parent: 'centos', familyId: 'rhel', name: 'Rocks Cluster', status: 'active', founded: 2000, country: 'United States', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://rocksclusters.org', description: 'RHEL-based HPC cluster distribution.' });
addDistro({ id: 'asianux', parent: 'rhel', familyId: 'rhel', name: 'Asianux', status: 'discontinued', founded: 2003, discontinuedAt: 2017, country: 'China', packageManager: 'rpm/yum', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', description: 'RHEL-based distro for Asian markets.' });

// ---- SUSE ----
addDistro({ id: 'sle', parent: 'suse', familyId: 'suse', name: 'SUSE Linux Enterprise', status: 'active', founded: 1994, country: 'Germany', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Proprietary', website: 'https://suse.com/products/server', wikipedia: 'https://en.wikipedia.org/wiki/SUSE_Linux_Enterprise', description: 'Enterprise server and desktop Linux by SUSE.' });
addDistro({ id: 'sled', parent: 'sle', familyId: 'suse', name: 'SUSE Linux Enterprise Desktop', status: 'active', founded: 2004, country: 'Germany', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Proprietary', website: 'https://suse.com/products/desktop', description: 'Enterprise desktop Linux by SUSE.' });
addDistro({ id: 'opensuse-leap', parent: 'opensuse', familyId: 'opensuse', name: 'openSUSE Leap', status: 'active', founded: 2015, country: 'Germany', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://opensuse.org', description: 'Regular-release openSUSE edition based on SUSE Linux Enterprise.' });
addDistro({ id: 'opensuse-tumbleweed', parent: 'opensuse', familyId: 'opensuse', name: 'openSUSE Tumbleweed', status: 'active', founded: 2014, country: 'Germany', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://opensuse.org', description: 'Rolling-release openSUSE edition with latest packages.' });
addDistro({ id: 'opensuse-microos', parent: 'opensuse', familyId: 'opensuse', name: 'openSUSE MicroOS', status: 'active', founded: 2019, country: 'Germany', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://opensuse.org', description: 'Transactionally-updated atomic openSUSE for containers.' });
addDistro({ id: 'geckolinux', parent: 'opensuse', familyId: 'opensuse', name: 'GeckoLinux', status: 'active', founded: 2015, country: 'Global', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://geckolinux.org', description: 'openSUSE-based distro with out-of-the-box desktop polish.' });
addDistro({ id: 'geckolinux-static', parent: 'geckolinux', familyId: 'opensuse', name: 'GeckoLinux Static', status: 'active', founded: 2015, country: 'Global', packageManager: 'zypper/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://geckolinux.org', description: 'Static (non-rolling) GeckoLinux edition based on openSUSE Leap.' });

// ---- Mageia / Mandriva ----
addDistro({ id: 'mageia', familyId: 'mageia', name: 'Mageia', status: 'active', founded: 2010, country: 'France', packageManager: 'urpmi/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://www.mageia.org', wikipedia: 'https://en.wikipedia.org/wiki/Mageia', description: 'Community fork of Mandriva Linux.' });
addDistro({ id: 'mageia-kde', parent: 'mageia', familyId: 'mageia', name: 'Mageia KDE', status: 'active', founded: 2010, country: 'France', packageManager: 'urpmi/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://www.mageia.org', description: 'Mageia edition with KDE Plasma desktop.' });
addDistro({ id: 'mageia-gnome', parent: 'mageia', familyId: 'mageia', name: 'Mageia GNOME', status: 'active', founded: 2010, country: 'France', packageManager: 'urpmi/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://www.mageia.org', description: 'Mageia edition with GNOME desktop.' });
addDistro({ id: 'rosa-fresh', parent: 'mandriva', familyId: 'rosa', name: 'ROSA Desktop Fresh', status: 'active', founded: 2011, country: 'Russia', packageManager: 'rpm/urpmi', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://rosalinux.ru', description: 'Russian Mandriva-based desktop distribution.' });
addDistro({ id: 'pclinuxos', familyId: 'pclinuxos', name: 'PCLinuxOS', status: 'active', founded: 2003, country: 'United Kingdom', packageManager: 'apt-rpm', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://pclinuxos.com', wikipedia: 'https://en.wikipedia.org/wiki/PCLinuxOS', description: 'Rolling release RPM-based distro for desktops.' });
addDistro({ id: 'pclinuxos-kde', parent: 'pclinuxos', familyId: 'pclinuxos', name: 'PCLinuxOS KDE', status: 'active', founded: 2003, country: 'United Kingdom', packageManager: 'apt-rpm', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://pclinuxos.com', description: 'PCLinuxOS edition with KDE Plasma.' });
addDistro({ id: 'pclinuxos-mate', parent: 'pclinuxos', familyId: 'pclinuxos', name: 'PCLinuxOS MATE', status: 'active', founded: 2007, country: 'United Kingdom', packageManager: 'apt-rpm', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://pclinuxos.com', description: 'PCLinuxOS edition with MATE desktop.' });
addDistro({ id: 'altlinux-spserver', parent: 'altlinux', familyId: 'altlinux', name: 'ALT SPServer', status: 'active', founded: 2001, country: 'Russia', packageManager: 'rpm/apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://altlinux.org', description: 'ALT Linux server edition.' });
addDistro({ id: 'altlinux-kworkstation', parent: 'altlinux', familyId: 'altlinux', name: 'ALT KWorkstation', status: 'active', founded: 2002, country: 'Russia', packageManager: 'rpm/apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://altlinux.org', description: 'ALT Linux workstation edition with KDE.' });
addDistro({ id: 'turbolinux', familyId: 'turbolinux', name: 'TurboLinux', status: 'discontinued', founded: 1992, discontinuedAt: 2010, country: 'Japan', packageManager: 'rpm', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://turbolinux.com', wikipedia: 'https://en.wikipedia.org/wiki/TurboLinux', description: 'Japanese RPM-based distribution.' });

// ---- Gentoo - add more ----
addDistro({ id: 'gentoo', familyId: 'gentoo', name: 'Gentoo Linux', status: 'active', founded: 2000, country: 'United States', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://gentoo.org', wikipedia: 'https://en.wikipedia.org/wiki/Gentoo_Linux', description: 'Source-based, highly customizable metadistribution.' });
addDistro({ id: 'gentoo-hardened', parent: 'gentoo', familyId: 'gentoo', name: 'Gentoo Hardened', status: 'active', founded: 2002, country: 'Global', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://wiki.gentoo.org', description: 'Gentoo with security-hardened toolchain and kernel.' });
addDistro({ id: 'gentoo-systemd', parent: 'gentoo', familyId: 'gentoo', name: 'Gentoo systemd', status: 'active', founded: 2012, country: 'Global', packageManager: 'portage/emerge', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://gentoo.org', description: 'Gentoo profile using systemd instead of OpenRC.' });
addDistro({ id: 'calculate', familyId: 'calculate', name: 'Calculate Linux', status: 'active', founded: 2006, country: 'Russia', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://www.calculate-linux.org', wikipedia: 'https://en.wikipedia.org/wiki/Calculate_Linux', description: 'Gentoo-based Russian distro for corporate use.' });
addDistro({ id: 'calculate-server', parent: 'calculate', familyId: 'calculate', name: 'Calculate Linux Server', status: 'active', founded: 2007, country: 'Russia', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://www.calculate-linux.org', description: 'Server edition of Calculate Linux.' });
addDistro({ id: 'calculate-directory', parent: 'calculate', familyId: 'calculate', name: 'Calculate Directory Server', status: 'active', founded: 2007, country: 'Russia', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://www.calculate-linux.org', description: 'Directory server edition of Calculate Linux.' });
addDistro({ id: 'calculate-media', parent: 'calculate', familyId: 'calculate', name: 'Calculate Media Center', status: 'active', founded: 2008, country: 'Russia', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://www.calculate-linux.org', description: 'Media center edition of Calculate Linux.' });
addDistro({ id: 'funtoo', familyId: 'funtoo', name: 'Funtoo Linux', status: 'discontinued', founded: 2008, discontinuedAt: 2023, country: 'United States', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://funtoo.org', wikipedia: 'https://en.wikipedia.org/wiki/Funtoo', description: 'Next-generation Gentoo by Daniel Robbins. Discontinued.' });
addDistro({ id: 'sabayon', familyId: 'sabayon', name: 'Sabayon Linux', status: 'discontinued', founded: 2005, discontinuedAt: 2024, country: 'Italy', packageManager: 'entropy/portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://sabayon.org', wikipedia: 'https://en.wikipedia.org/wiki/Sabayon_Linux', description: 'Beginner-friendly Gentoo-based binary distribution. Discontinued.' });
addDistro({ id: 'pentoo', familyId: 'pentoo', name: 'Pentoo', status: 'active', founded: 2009, country: 'Global', packageManager: 'portage/emerge', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://pentoo.ch', description: 'Gentoo-based penetration-testing Live CD.' });
addDistro({ id: 'coreos', familyId: 'coreos', name: 'Container Linux by CoreOS', status: 'discontinued', founded: 2013, discontinuedAt: 2020, country: 'United States', packageManager: 'portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://coreos.com', wikipedia: 'https://en.wikipedia.org/wiki/CoreOS', description: 'Container-focused Linux for clustered deployments. Discontinued.' });
addDistro({ id: 'flatcar', parent: 'coreos', familyId: 'coreos', name: 'Flatcar Container Linux', status: 'active', founded: 2020, country: 'United States', packageManager: 'portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://flatcar.org', description: 'Community fork of CoreOS Container Linux.' });
addDistro({ id: 'chromiumos', parent: 'gentoo', familyId: 'gentoo', name: 'Chromium OS', status: 'active', founded: 2009, country: 'United States', packageManager: 'portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://chromium.org/chromium-os', wikipedia: 'https://en.wikipedia.org/wiki/ChromiumOS', description: 'Open-source version of Google Chrome OS.' });
addDistro({ id: 'chromeos', familyId: 'chromeos', name: 'ChromeOS', status: 'active', founded: 2009, country: 'United States', packageManager: 'portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Proprietary', website: 'https://chromeos.google', wikipedia: 'https://en.wikipedia.org/wiki/ChromeOS', description: 'Google\'s Gentoo-based OS for Chromebooks.' });
addDistro({ id: 'chromeos-flex', parent: 'chromeos', familyId: 'chromeos', name: 'ChromeOS Flex', status: 'active', founded: 2022, country: 'United States', packageManager: 'portage', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://chromeos.google/products/flex', description: 'ChromeOS edition for older PCs and Macs.' });

// ---- Slackware - add more ----
addDistro({ id: 'slackware', familyId: 'slackware', name: 'Slackware', status: 'active', founded: 1993, country: 'United States', packageManager: 'pkgtool/slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://www.slackware.com', wikipedia: 'https://en.wikipedia.org/wiki/Slackware', description: 'One of the oldest actively maintained Linux distributions.' });
addDistro({ id: 'slackware-current', parent: 'slackware', familyId: 'slackware', name: 'Slackware Current', status: 'active', founded: 1993, country: 'United States', packageManager: 'pkgtool/slackpkg', initSystem: 'BSD-style', releaseModel: 'rolling', license: 'Free', website: 'https://www.slackware.com', description: 'Rolling development branch of Slackware.' });
addDistro({ id: 'salix', familyId: 'salix', name: 'Salix OS', status: 'active', founded: 2005, country: 'Global', packageManager: 'slackpkg/gslapt', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://salixos.org', wikipedia: 'https://en.wikipedia.org/wiki/Salix_OS', description: 'Slackware-based desktop distribution with Xfce.' });
addDistro({ id: 'salix-kde', parent: 'salix', familyId: 'salix', name: 'Salix KDE', status: 'active', founded: 2005, country: 'Global', packageManager: 'slackpkg/gslapt', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://salixos.org', description: 'Salix edition with KDE desktop.' });
addDistro({ id: 'salix-lxde', parent: 'salix', familyId: 'salix', name: 'Salix LXDE', status: 'active', founded: 2008, country: 'Global', packageManager: 'slackpkg/gslapt', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://salixos.org', description: 'Lightweight Salix edition with LXDE.' });
addDistro({ id: 'absolute', familyId: 'absolute', name: 'Absolute Linux', status: 'discontinued', founded: 2002, discontinuedAt: 2018, country: 'United States', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://absolutelinux.org', description: 'Lightweight Slackware-based distro. Discontinued.' });
addDistro({ id: 'vector', familyId: 'vector', name: 'VectorLinux', status: 'discontinued', founded: 1996, discontinuedAt: 2017, country: 'Canada', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://vectorlinux.com', wikipedia: 'https://en.wikipedia.org/wiki/VectorLinux', description: 'Slackware-based distro for casual users. Discontinued.' });
addDistro({ id: 'zenwalk', familyId: 'zenwalk', name: 'Zenwalk Linux', status: 'active', founded: 2004, country: 'France', packageManager: 'netpkg/slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://zenwalk.org', wikipedia: 'https://en.wikipedia.org/wiki/Zenwalk', description: 'Lightweight Slackware-based distro with Xfce.' });
addDistro({ id: 'slax', familyId: 'slax', name: 'Slax', status: 'active', founded: 2002, country: 'Czech Republic', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'rolling', license: 'Free', website: 'https://slax.org', wikipedia: 'https://en.wikipedia.org/wiki/Slax', description: 'Portable modular live Linux distribution.' });
addDistro({ id: 'porteus', familyId: 'porteus', name: 'Porteus', status: 'active', founded: 2010, country: 'Global', packageManager: 'slackpkg/usm', initSystem: 'BSD-style', releaseModel: 'rolling', license: 'Free', website: 'https://porteus.org', wikipedia: 'https://en.wikipedia.org/wiki/Porteus', description: 'Small, fast Slackware-based portable Linux.' });
addDistro({ id: 'slitaz', familyId: 'slitaz', name: 'SliTaz', status: 'active', founded: 2007, country: 'France', packageManager: 'tazpkg', initSystem: 'BSD-style', releaseModel: 'rolling', license: 'Free', website: 'https://slitaz.org', wikipedia: 'https://en.wikipedia.org/wiki/SliTaz', description: 'Ultra-lightweight Linux distribution under 40MB.' });
addDistro({ id: 'nimblex', parent: 'slackware', familyId: 'slackware', name: 'NimbleX', status: 'discontinued', founded: 2005, discontinuedAt: 2013, country: 'Romania', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', website: 'https://nimblex.net', description: 'Customizable Slackware-based live distro.' });
addDistro({ id: 'slackintosh', parent: 'slackware', familyId: 'slackware', name: 'Slackintosh', status: 'discontinued', founded: 2000, discontinuedAt: 2012, country: 'Global', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', description: 'Unofficial port of Slackware to PowerPC.' });
addDistro({ id: 'kateos', parent: 'slackware', familyId: 'slackware', name: 'KateOS', status: 'discontinued', founded: 2005, discontinuedAt: 2010, country: 'Poland', packageManager: 'slackpkg', initSystem: 'BSD-style', releaseModel: 'fixed', license: 'Free', description: 'Desktop Slackware derivative with Xfce.' });

// ---- Alpine ----
addDistro({ id: 'alpine', familyId: 'alpine', name: 'Alpine Linux', status: 'active', founded: 2005, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://alpinelinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Alpine_Linux', description: 'Security-oriented, lightweight Linux based on musl and BusyBox.' });
addDistro({ id: 'alpine-standard', parent: 'alpine', familyId: 'alpine', name: 'Alpine Standard', status: 'active', founded: 2005, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://alpinelinux.org', description: 'Standard Alpine Linux for x86_64.' });
addDistro({ id: 'alpine-virt', parent: 'alpine', familyId: 'alpine', name: 'Alpine Virtual', status: 'active', founded: 2010, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://alpinelinux.org', description: 'Minimal Alpine for virtual machines.' });
addDistro({ id: 'postmarketos', familyId: 'postmarketos', name: 'postmarketOS', status: 'active', founded: 2017, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://postmarketos.org', wikipedia: 'https://en.wikipedia.org/wiki/PostmarketOS', description: 'Alpine-based OS for mobile phones.' });
addDistro({ id: 'postmarketos-phosh', parent: 'postmarketos', familyId: 'postmarketos', name: 'postmarketOS Phosh', status: 'active', founded: 2019, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://postmarketos.org', description: 'postmarketOS edition with Phosh mobile UI.' });
addDistro({ id: 'postmarketos-plasma', parent: 'postmarketos', familyId: 'postmarketos', name: 'postmarketOS Plasma Mobile', status: 'active', founded: 2019, country: 'Global', packageManager: 'apk', initSystem: 'OpenRC', releaseModel: 'rolling', license: 'Free', website: 'https://postmarketos.org', description: 'postmarketOS edition with Plasma Mobile.' });

// ---- Void, NixOS, Solus, Puppy ----
addDistro({ id: 'void', familyId: 'void', name: 'Void Linux', status: 'active', founded: 2008, country: 'Netherlands', packageManager: 'xbps', initSystem: 'runit', releaseModel: 'rolling', license: 'Free', website: 'https://voidlinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Void_Linux', description: 'Independent rolling distro with XBPS package manager and runit.' });
addDistro({ id: 'void-glibc', parent: 'void', familyId: 'void', name: 'Void Linux glibc', status: 'active', founded: 2008, country: 'Netherlands', packageManager: 'xbps', initSystem: 'runit', releaseModel: 'rolling', license: 'Free', website: 'https://voidlinux.org', description: 'Void with glibc (default).' });
addDistro({ id: 'void-musl', parent: 'void', familyId: 'void', name: 'Void Linux musl', status: 'active', founded: 2008, country: 'Netherlands', packageManager: 'xbps', initSystem: 'runit', releaseModel: 'rolling', license: 'Free', website: 'https://voidlinux.org', description: 'Void with musl libc.' });
addDistro({ id: 'nixos', familyId: 'nixos', name: 'NixOS', status: 'active', founded: 2003, country: 'Netherlands', packageManager: 'nix', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://nixos.org', wikipedia: 'https://en.wikipedia.org/wiki/NixOS', description: 'Declarative, purely functional distribution with atomic upgrades.' });
addDistro({ id: 'nixos-unstable', parent: 'nixos', familyId: 'nixos', name: 'NixOS Unstable', status: 'active', founded: 2003, country: 'Netherlands', packageManager: 'nix', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://nixos.org', description: 'NixOS rolling/unstable channel.' });
addDistro({ id: 'solus', familyId: 'solus', name: 'Solus', status: 'active', founded: 2012, country: 'United States', packageManager: 'eopkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://getsol.us', wikipedia: 'https://en.wikipedia.org/wiki/Solus_(operating_system)', description: 'Independent rolling distro with Budgie desktop.' });
addDistro({ id: 'solus-budgie', parent: 'solus', familyId: 'solus', name: 'Solus Budgie', status: 'active', founded: 2012, country: 'United States', packageManager: 'eopkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://getsol.us', description: 'Solus edition with Budgie desktop.' });
addDistro({ id: 'solus-gnome', parent: 'solus', familyId: 'solus', name: 'Solus GNOME', status: 'active', founded: 2020, country: 'United States', packageManager: 'eopkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://getsol.us', description: 'Solus edition with GNOME desktop.' });
addDistro({ id: 'solus-plasma', parent: 'solus', familyId: 'solus', name: 'Solus Plasma', status: 'active', founded: 2017, country: 'United States', packageManager: 'eopkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://getsol.us', description: 'Solus edition with KDE Plasma.' });
addDistro({ id: 'solus-mate', parent: 'solus', familyId: 'solus', name: 'Solus MATE', status: 'active', founded: 2015, country: 'United States', packageManager: 'eopkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://getsol.us', description: 'Solus edition with MATE desktop.' });
addDistro({ id: 'puppy', familyId: 'puppy', name: 'Puppy Linux', status: 'active', founded: 2003, country: 'Australia', packageManager: 'puppy-pkg', initSystem: 'BusyBox', releaseModel: 'rolling', license: 'Free', website: 'https://puppylinux.com', wikipedia: 'https://en.wikipedia.org/wiki/Puppy_Linux', description: 'Tiny, easy-to-use Linux that runs entirely from RAM.' });

// ---- Independent distributions ----
addDistro({ id: 'clear-linux', familyId: 'clear-linux', name: 'Clear Linux', status: 'discontinued', founded: 2015, discontinuedAt: 2024, country: 'United States', packageManager: 'swupd', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://clearlinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Clear_Linux', description: 'Intel\'s performance-optimized rolling release. Discontinued.' });
addDistro({ id: 'crux', familyId: 'crux', name: 'CRUX', status: 'active', founded: 2001, country: 'Sweden', packageManager: 'pkgutils/prt-get', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://crux.nu', wikipedia: 'https://en.wikipedia.org/wiki/CRUX', description: 'Lightweight, x86-64 optimized Linux, inspiration for Arch.' });
addDistro({ id: 'gobolinux', familyId: 'gobolinux', name: 'GoboLinux', status: 'active', founded: 2003, country: 'Brazil', packageManager: 'Gobo/Compile', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://gobolinux.org', wikipedia: 'https://en.wikipedia.org/wiki/GoboLinux', description: 'Alternative filesystem hierarchy where each app lives in its own folder.' });
addDistro({ id: 'tinycore', familyId: 'tinycore', name: 'Tiny Core Linux', status: 'active', founded: 2009, country: 'Canada', packageManager: 'tce', initSystem: 'busybox', releaseModel: 'rolling', license: 'Free', website: 'https://tinycorelinux.net', wikipedia: 'https://en.wikipedia.org/wiki/Tiny_Core_Linux', description: 'Minimalist (~10 MB) Linux distribution.' });
addDistro({ id: 'tinycore-core', parent: 'tinycore', familyId: 'tinycore', name: 'Core', status: 'active', founded: 2009, country: 'Canada', packageManager: 'tce', initSystem: 'busybox', releaseModel: 'rolling', license: 'Free', website: 'https://tinycorelinux.net', description: 'Tiny Core without X11 (~8 MB).' });
addDistro({ id: 'tinycore-corepure', parent: 'tinycore', familyId: 'tinycore', name: 'CorePure64', status: 'active', founded: 2015, country: 'Canada', packageManager: 'tce', initSystem: 'busybox', releaseModel: 'rolling', license: 'Free', website: 'https://tinycorelinux.net', description: '64-bit edition of Tiny Core.' });
addDistro({ id: 'dragora', familyId: 'dragora', name: 'Dragora GNU/Linux-libre', status: 'active', founded: 2008, country: 'Argentina', packageManager: 'pkg', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://dragora.org', description: 'Free software distribution written from scratch.' });
addDistro({ id: 'guix', familyId: 'guix', name: 'GNU Guix System', status: 'active', founded: 2012, country: 'Global', packageManager: 'guix', initSystem: 'GNU Shepherd', releaseModel: 'rolling', license: 'Free', website: 'https://guix.gnu.org', wikipedia: 'https://en.wikipedia.org/wiki/GNU_Guix_System', description: 'Declarative GNU distribution with purely functional package management.' });
addDistro({ id: 'bedrock', familyId: 'bedrock', name: 'Bedrock Linux', status: 'active', founded: 2012, country: 'Global', packageManager: 'Multiple', initSystem: 'Multiple', releaseModel: 'rolling', license: 'Free', website: 'https://bedrocklinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Bedrock_Linux', description: 'Meta-distribution that allows mixing components from other distros.' });
addDistro({ id: 'chimera', familyId: 'chimera', name: 'Chimera Linux', status: 'active', founded: 2021, country: 'Global', packageManager: 'apk', initSystem: 'dinit', releaseModel: 'rolling', license: 'Free', website: 'https://chimera-linux.org', description: 'Independent distro with FreeBSD userland, LLVM, and musl.' });
addDistro({ id: '4mlinux', familyId: '4mlinux', name: '4MLinux', status: 'active', founded: 2010, country: 'Poland', packageManager: 'custom', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://4mlinux.com', description: 'Small independent distro focusing on maintenance, multimedia, and games.' });
addDistro({ id: '4mlinux-server', parent: '4mlinux', familyId: '4mlinux', name: '4MLinux Server', status: 'active', founded: 2012, country: 'Poland', packageManager: 'custom', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://4mlinux.com', description: 'Server edition of 4MLinux.' });

// ---- Android-based ----
addDistro({ id: 'lineageos', familyId: 'lineageos', name: 'LineageOS', status: 'active', founded: 2016, country: 'Global', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://lineageos.org', wikipedia: 'https://en.wikipedia.org/wiki/LineageOS', description: 'Free and open-source Android-based OS for smartphones.' });
addDistro({ id: 'lineageos-microg', parent: 'lineageos', familyId: 'lineageos', name: 'LineageOS for microG', status: 'active', founded: 2017, country: 'Global', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://lineage.microg.org', description: 'LineageOS with microG services instead of Google apps.' });
addDistro({ id: 'grapheneos', familyId: 'grapheneos', name: 'GrapheneOS', status: 'active', founded: 2014, country: 'United States', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://grapheneos.org', wikipedia: 'https://en.wikipedia.org/wiki/GrapheneOS', description: 'Privacy and security hardened Android-based OS.' });
addDistro({ id: 'calyxos', familyId: 'calyxos', name: 'CalyxOS', status: 'active', founded: 2018, country: 'United States', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://calyxos.org', wikipedia: 'https://en.wikipedia.org/wiki/CalyxOS', description: 'Android-based OS focused on privacy and security.' });
addDistro({ id: 'e-os', familyId: 'e-os', name: '/e/ OS', status: 'active', founded: 2018, country: 'France', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://e.foundation', wikipedia: 'https://en.wikipedia.org/wiki//e/(operating_system)', description: 'De-Googled Android-based mobile operating system.' });
addDistro({ id: 'replicant', familyId: 'replicant', name: 'Replicant', status: 'active', founded: 2010, country: 'Global', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://replicant.us', wikipedia: 'https://en.wikipedia.org/wiki/Replicant_(operating_system)', description: 'Fully free Android-based OS, all proprietary parts removed.' });
addDistro({ id: 'omnirom', parent: 'lineageos', familyId: 'lineageos', name: 'OmniROM', status: 'active', founded: 2013, country: 'Global', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://omnirom.org', description: 'Community-built Android ROM with customizable features.' });
addDistro({ id: 'paranoid-android', parent: 'lineageos', familyId: 'lineageos', name: 'Paranoid Android', status: 'active', founded: 2012, country: 'Global', packageManager: 'APK', initSystem: 'Android init', releaseModel: 'rolling', license: 'Free', website: 'https://paranoidandroid.co', description: 'Android custom ROM focused on performance and design.' });

// ---- OpenWrt ----
addDistro({ id: 'openwrt', familyId: 'openwrt', name: 'OpenWrt', status: 'active', founded: 2004, country: 'Global', packageManager: 'opkg', initSystem: 'procd', releaseModel: 'rolling', license: 'Free', website: 'https://openwrt.org', wikipedia: 'https://en.wikipedia.org/wiki/OpenWrt', description: 'Linux distribution for routers and embedded devices.' });
addDistro({ id: 'lede', parent: 'openwrt', familyId: 'openwrt', name: 'LEDE', status: 'active', founded: 2016, country: 'Global', packageManager: 'opkg', initSystem: 'procd', releaseModel: 'rolling', license: 'Free', website: 'https://lede-project.org', wikipedia: 'https://en.wikipedia.org/wiki/LEDE', description: 'Fork and successor to OpenWrt, later merged back.' });
addDistro({ id: 'ddwrt', parent: 'openwrt', familyId: 'openwrt', name: 'DD-WRT', status: 'active', founded: 2005, country: 'United States', packageManager: 'ipkg', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://dd-wrt.com', wikipedia: 'https://en.wikipedia.org/wiki/DD-WRT', description: 'Embedded Linux for routers and wireless access points.' });

// ---- Historical/special ----
addDistro({ id: 'softlanding', familyId: 'slackware', name: 'Softlanding Linux System', status: 'discontinued', founded: 1992, discontinuedAt: 1994, country: 'United States', packageManager: 'None', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', description: 'One of the earliest Linux distributions; Slackware was based on it.' });
addDistro({ id: 'yggdrasil', familyId: 'debian', name: 'Yggdrasil Linux/GNU/X', status: 'discontinued', founded: 1992, discontinuedAt: 1995, country: 'United States', packageManager: 'None', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', wikipedia: 'https://en.wikipedia.org/wiki/Yggdrasil_Linux/GNU/X', description: 'One of the oldest Linux distributions. Discontinued in 1995.' });
addDistro({ id: 'mcc-interim', familyId: 'debian', name: 'MCC Interim Linux', status: 'discontinued', founded: 1992, discontinuedAt: 1993, country: 'United Kingdom', packageManager: 'None', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', wikipedia: 'https://en.wikipedia.org/wiki/MCC_Interim_Linux', description: 'Possibly the first Linux distribution, by Manchester Computing Centre.' });
addDistro({ id: 'tomsrtbt', familyId: 'slackware', name: 'tomsrtbt', status: 'discontinued', founded: 1997, discontinuedAt: 2002, country: 'United States', packageManager: 'None', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', description: 'Root boot from floppy disk. One of the smallest Linux distros ever.' });
addDistro({ id: 'smoothwall', familyId: 'openwrt', name: 'SmoothWall Express', status: 'active', founded: 2001, country: 'United Kingdom', packageManager: 'None', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://smoothwall.org', wikipedia: 'https://en.wikipedia.org/wiki/SmoothWall', description: 'Open-source router and firewall distribution.' });
addDistro({ id: 'ipfire', familyId: 'openwrt', name: 'IPFire', status: 'active', founded: 2005, country: 'Germany', packageManager: 'pakfire', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://ipfire.org', wikipedia: 'https://en.wikipedia.org/wiki/IPFire', description: 'Linux distribution for firewalls and routers.' });
addDistro({ id: 'pfsense', familyId: 'openwrt', name: 'pfSense', status: 'active', founded: 2006, country: 'United States', packageManager: 'pkg', initSystem: 'sysvinit', releaseModel: 'fixed', license: 'Free', website: 'https://pfsense.org', wikipedia: 'https://en.wikipedia.org/wiki/PfSense', description: 'Firewall and router distribution based on FreeBSD.' });

// ---- Misc additional ----
addDistro({ id: 'linuxconsole', familyId: 'debian', name: 'LinuxConsole', status: 'active', founded: 2007, country: 'France', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://linuxconsole.org', description: 'Lightweight Debian-based distro for old computers.' });
addDistro({ id: 'tizen', familyId: 'debian', name: 'Tizen', status: 'active', founded: 2011, country: 'South Korea', packageManager: 'rpm', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://tizen.org', wikipedia: 'https://en.wikipedia.org/wiki/Tizen', description: 'Linux-based mobile OS backed by Samsung.' });
addDistro({ id: 'kaios', familyId: 'debian', name: 'KaiOS', status: 'active', founded: 2017, country: 'United States', packageManager: 'JIO', initSystem: 'B2G', releaseModel: 'rolling', license: 'Proprietary', website: 'https://kaiostech.com', wikipedia: 'https://en.wikipedia.org/wiki/KaiOS', description: 'Mobile OS based on the Linux kernel for feature phones.' });
addDistro({ id: 'paldo', familyId: 'debian', name: 'paldo', status: 'active', founded: 2007, country: 'Global', packageManager: 'upkg', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://paldo.org', description: 'Independent rolling release with GNOME desktop.' });

// ---- Calculate additional distros ----
addDistro({ id: 'kwort', parent: 'crux', familyId: 'crux', name: 'Kwort', status: 'active', founded: 2005, country: 'Brazil', packageManager: 'kpkg', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://kwort.org', description: 'CRUX-based distro with the KISS principle.' });
addDistro({ id: 'sourcemage', familyId: 'crux', name: 'Source Mage', status: 'active', founded: 2003, country: 'Global', packageManager: 'cast/sorcery', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://sourcemage.org', description: 'Source-based distribution descended from Sorcerer.' });
addDistro({ id: 'foresight', familyId: 'crux', name: 'Foresight Linux', status: 'discontinued', founded: 2006, discontinuedAt: 2015, country: 'United States', packageManager: 'conary', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', description: 'Rolling release built around the Conary package manager.' });

// ---- KaOS ----
addDistro({ id: 'kaos', familyId: 'kaos', name: 'KaOS', status: 'active', founded: 2009, country: 'Global', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://kaosx.us', wikipedia: 'https://en.wikipedia.org/wiki/KaOS', description: 'Independent rolling-release focused on KDE and Qt.' });
addDistro({ id: 'chakra', familyId: 'chakra', name: 'Chakra Linux', status: 'discontinued', founded: 2006, discontinuedAt: 2022, country: 'Germany', packageManager: 'pacman', initSystem: 'systemd', releaseModel: 'rolling', license: 'Free', website: 'https://chakralinux.org', wikipedia: 'https://en.wikipedia.org/wiki/Chakra_Linux', description: 'Arch-based distro focused on KDE. Discontinued.' });

// ---- Frugalware / RPM others ----
addDistro({ id: 'frugalware', familyId: 'slackware', name: 'Frugalware Linux', status: 'discontinued', founded: 2004, discontinuedAt: 2020, country: 'Hungary', packageManager: 'pacman-g2', initSystem: 'sysvinit', releaseModel: 'rolling', license: 'Free', website: 'https://frugalware.org', description: 'General-purpose distro with Slackware influences.' });
addDistro({ id: 'moblin', parent: 'fedora', familyId: 'fedora', name: 'Moblin', status: 'discontinued', founded: 2007, discontinuedAt: 2010, country: 'United States', packageManager: 'rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', wikipedia: 'https://en.wikipedia.org/wiki/Moblin', description: 'Intel Atom-focused mobile Linux. Merged into MeeGo.' });
addDistro({ id: 'meego', parent: 'fedora', familyId: 'fedora', name: 'MeeGo', status: 'discontinued', founded: 2010, discontinuedAt: 2011, country: 'United States', packageManager: 'rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', wikipedia: 'https://en.wikipedia.org/wiki/MeeGo', description: 'Intel and Nokia mobile Linux. Superseded by Tizen.' });

// ---- More Ubuntu flavored that need a parent of current ubuntu ----
addDistro({ id: 'gobuntu', parent: 'ubuntu', familyId: 'ubuntu', name: 'Gobuntu', status: 'discontinued', founded: 2007, discontinuedAt: 2008, country: 'United Kingdom', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://ubuntu.com', description: 'Official Ubuntu derivative with only free software.' });
addDistro({ id: 'mythbuntu', parent: 'ubuntu', familyId: 'ubuntu', name: 'Mythbuntu', status: 'discontinued', founded: 2007, discontinuedAt: 2016, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://mythbuntu.org', description: 'Ubuntu-based HTPC distribution with MythTV.' });
addDistro({ id: 'jolicloud', parent: 'ubuntu', familyId: 'ubuntu', name: 'Joli OS', status: 'discontinued', founded: 2009, discontinuedAt: 2014, country: 'France', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://jolicloud.com', wikipedia: 'https://en.wikipedia.org/wiki/Joli_OS', description: 'Cloud-based netbook Ubuntu derivative.' });
addDistro({ id: 'goobuntu', parent: 'ubuntu', familyId: 'ubuntu', name: 'Goobuntu', status: 'discontinued', founded: 2006, discontinuedAt: 2016, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', wikipedia: 'https://en.wikipedia.org/wiki/Goobuntu', description: 'Google\'s internal Ubuntu-based distribution.' });
addDistro({ id: 'hannah-linux', parent: 'ubuntu', familyId: 'ubuntu', name: 'Hannah Linux', status: 'discontinued', founded: 2007, discontinuedAt: 2009, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', description: 'Ubuntu-based distro themed after Hannah Montana. Discontinued.' });
addDistro({ id: 'linuxmce', parent: 'kubuntu', familyId: 'ubuntu', name: 'LinuxMCE', status: 'discontinued', founded: 2006, discontinuedAt: 2015, country: 'United States', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://linuxmce.org', description: 'Kubuntu-based home media center with automation features.' });
addDistro({ id: 'nubuntu', parent: 'ubuntu', familyId: 'ubuntu', name: 'nUbuntu', status: 'discontinued', founded: 2005, discontinuedAt: 2008, country: 'Global', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', description: 'Ubuntu-based security testing distro. Discontinued.' });
addDistro({ id: 'poseidon', parent: 'ubuntu', familyId: 'ubuntu', name: 'Poseidon Linux', status: 'discontinued', founded: 2005, discontinuedAt: 2018, country: 'Brazil', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://poseidonlinux.org', description: 'Ubuntu-based for academic and scientific use.' });
addDistro({ id: 'supergamer', parent: 'ubuntu', familyId: 'ubuntu', name: 'SuperGamer', status: 'discontinued', founded: 2005, discontinuedAt: 2013, country: 'Canada', packageManager: 'apt', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', description: 'Live DVD gaming distribution based on VectorLinux then Ubuntu.' });
addDistro({ id: 'vine', parent: 'ubuntu', familyId: 'ubuntu', name: 'Vine Linux', status: 'active', founded: 1998, country: 'Japan', packageManager: 'apt/rpm', initSystem: 'systemd', releaseModel: 'fixed', license: 'Free', website: 'https://vinelinux.org', description: 'Japanese desktop distribution with RPM packaging.' });

/* ==========================================================================
   WRITE OUTPUT
   ========================================================================== */

writeFileSync(SRC, JSON.stringify(current, null, 2));
console.log(`✓ Wrote ${SRC}`);
console.log(`  ${current.families.length} families`);
console.log(`  ${current.distros.length} distros`);
console.log(`  Active: ${current.distros.filter((d) => d.status === 'active').length}`);
console.log(`  Discontinued: ${current.distros.filter((d) => d.status === 'discontinued').length}`);
console.log('');
console.log('Now run: npm run build:data');
